### PR TITLE
Add atoum

### PR DESCRIPTION
**Pull request by Hywan**
[atoum](http://atoum.org/atoum) is another very important unit test framework, used by several big projects (like [Pickle](https://github.com/FriendsOfPHP/pickle/) for example). I think it deserves a place in the list ;-).

### CODE REVIEW

**Comment by jubianchi** [comment]
:+1:

**Comment by reinink** [comment]
Cool, added. Thanks for contributed to this project!

**Comment by Hywan** [comment]
Thanks :-).

**Pull request merged**
